// var testsContext = require.context('./', true, /\.spec\.js$/)
// testsContext.keys().forEach(testsContext)
require('./calls.spec.js')
require('./mock.spec.js')
require('./stuct.spec.js')
require('./rules.spec.js')
require('./rulesManage.spec.js')
require('./network.spec.js')
require('./index.spec.js')
